title: SwiftUI Patterns
description: A collection of SwiftUI patterns and best practices
author: Gabriel Handford
url: "https://gabriel.github.io"
baseurl: "/swiftui-patterns"
remote_theme: pages-themes/minimal@v0.2.0

# GitHub Pages settings
# theme: jekyll-theme-cayman
plugins:
  - jekyll-relative-links
  - jekyll-seo-tag
  - jekyll-remote-theme

# Navigation
nav:
  - title: Navigation
    url: /docs/navigation/
  - title: Dependencies
    url: /docs/dependencies/
  - title: Awesome Swift Libraries
    url: /docs/awesome/
  - title: Testing
    url: /docs/testing/  

# Social links
social:
  github: gabriel
  